### ISSUE TITLE
Error when changing buffers in a window when there's a window split.

### ISSUE THREAD

**Issue by oblitum** [embear/vim-longlines#1]
This is the message I get when I have two files loaded, a window split, and try to change buffers in one of the windows:

```
Error detected while processing function longline#show..longline#hide:
line    2:
E803: ID not found: 6
```

**Comment by oblitum** [comment]
This is a related issue and fix, not sure whether it's clean:

https://github.com/nathanaelkane/vim-indent-guides/issues/18#issuecomment-1968877

**Comment by embear** [comment]
Sorry, but I think you are using a different plugin with a similar name and you found a bug is in that plugin: https://github.com/Soares/longline.vim

**Comment by oblitum** [comment]
@embear ah, I'm sorry!

**Comment by oblitum** [comment]
and in the meantime it looks like to have been fixed already =)
